assets:
- drupal7.201808151534367827.gz
steps:
- name: Site setup
  plugin: Drupal
  database: drupal7.201808151534367827.gz 
  databaseGzipped: true
  databaseUpdates: true
  clearCaches: true
  varnish: true
  settingsAppend: |
    $conf['cache_backends'][] = 'sites/all/modules/varnish/varnish.cache.inc';
- name: Generate login link
  command: 'drush uli'

