assets:
- drupal7.201808151534367827.gz
- my-varnish.txt
steps:
- name: Site setup
  plugin: Drupal
  database: drupal7.201808151534367827.gz 
  databaseGzipped: true
  databaseUpdates: true
  clearCaches: true
  varnish:
    enable: true
    path: '/assets/my-varnish.txt'
- name: Generate login link
  command: 'drush uli'

